[workspace]
members = [
    "arrays",
    "bigger",
    "capitalizing",
    "card_deck",
    "changes",
    "circle",
    "collect",
    "edit_distance",
    "hashing",
    "is_anagram",
    "simple_hash",
    "string_permutation",
    "strings",
]
resolver = "2"
