[workspace]
members = [
    "borrow",
    "doubtful",
    "to_url",
    "string_literals",
    "name_initials",
    "ownership",
    "copy",
    "borrow_me_the_reference",
    "tic_tac_toe",
    "arrange_it",
    "armstrong_number",

]
