[workspace]
members = [
    "unwrap_or_expect",
    "panic",
    "handling",
    "profanity_filter",
    "question_mark",
    "banner",
    "cipher",
    "error_types",
    "boxing_todo",
    "binary_search",
]
